version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - caller-data:/var/lib/postgresql/data
    networks:
      - caller-network

  bot-a:
    build:
      context: ./Caller
    container_name: caller_bot
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      BOT_TOKEN: ${CALLER_TOKEN}
    networks:
      - caller-network

volumes:
  caller-data:

networks:
  caller-network:
