version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network

  bot-a:
    build: .
    container_name: caller_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      BOT_TOKEN: ${CALLER_TOKEN}
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - backups:/app/backups
    networks:
      - bot-network

volumes:
  pgdata:
  backups:

networks:
  bot-network:
